version: "3.9"
services:
  structurizr:
    image: structurizr/lite
    environment:
      - MODEL=${MODEL?MODEL_NOT_SET}
    ports:
      - "8080:8080"
    volumes:
      - ./$MODEL:/usr/local/structurizr
